spring.application.name=familyspencesapi

spring.datasource.url=jdbc:postgresql://db.pmxfidynceexcalsduio.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=brahian2004
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

