budget.procesar.exchange-name=x.budget.exchange
budget.procesar.routing-key.create=budget.create
budget.procesar.routing-key.update=budget.update
budget.procesar.routing-key.delete=budget.delete
budget.procesar.queue-create=budget.create.queue
budget.procesar.queue-update=budget.update.queue
budget.procesar.queue-delete=budget.delete.queue